### ISSUE TITLE
Invalid gemspec homepage

### ISSUE THREAD

**Issue by heatherbooker** [marina101/vast-analyzer#3]
Hi! Great gem you have here. :) I just have a quick question; while trying to set up a project using this gem, running `bundle install` gives me the following output:

```
Fetching gem metadata from https://rubygems.org/.......
You have one or more invalid gemspecs that need to be fixed.
The gemspec at
/home/h/.gem/ruby/bundler/gems/vast-analyzer-b0cae0d46e7b/vast_analyzer.gemspec
is not valid. Please fix this gemspec.
The validation error was
'"TODO: Put your gem's website or public repo URL here."
is not a valid HTTP URI'
```

I'm not sure why it cares so much about this, but just wanted to let you know and also ask if you have any clues as to how I can get around this error? I am no ruby pro so it might be very obvious but I am missing it!

Thanks!

**Comment by marina101** [comment]
Hey! I tried but cannot reproduce this error. Are you sure you're using this repository as your upstream and not a fork?
